# Generated by Django 4.1.3 on 2022-11-28 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import transaction.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('initial_amount', models.FloatField(default=0.0)),
                ('type', models.IntegerField(choices=[(101, 'SAVINGS'), (102, 'INVESTMENT'), (103, 'FIXED DEPOSIT')], default=transaction.constants.AccountType['SAVINGS'])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, default=None, null=True)),
                ('type', models.IntegerField(choices=[(101, 'INCOME'), (102, 'EXPENSE')], default=transaction.constants.TransactionType['INCOME'])),
                ('category', models.IntegerField(choices=[(101, 'SALARY'), (102, 'GIFT'), (103, 'INTREST'), (104, 'RETURN'), (105, 'TRAVEL'), (106, 'ENTERTAINMENT'), (107, 'VEHICLE'), (108, 'SHOPPING'), (109, 'FOOD'), (110, 'INVESTMENT')], default=transaction.constants.Category['FOOD'])),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('comment', models.TextField(blank=True, default='', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transaction.account')),
            ],
        ),
    ]
