# Generated by Django 4.1.3 on 2022-11-30 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 30, 5, 53, 54, 376420), null=True),
        ),
    ]
