# Generated by Django 4.1.3 on 2022-11-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
